#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Pixeon.Schedule.Laudo/Pixeon.Schedule.Laudo.csproj", "Pixeon.Schedule.Laudo/"]
RUN dotnet restore "Pixeon.Schedule.Laudo/Pixeon.Schedule.Laudo.csproj"
COPY . .
WORKDIR "/src/Pixeon.Schedule.Laudo"
RUN dotnet build "Pixeon.Schedule.Laudo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Pixeon.Schedule.Laudo.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Pixeon.Schedule.Laudo.dll"]