#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Pixeon.Api/Pixeon.Api.csproj", "Pixeon.Api/"]
RUN dotnet restore "Pixeon.Api/Pixeon.Api.csproj"
COPY . .
WORKDIR "/src/Pixeon.Api"
RUN dotnet build "Pixeon.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Pixeon.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Pixeon.Api.dll"]